exclude:
- /.github/changelog.js
- /.sandstorm/.*
- /.scripts/set-version.js
- /.scripts/start-xvfb.sh
- /.scripts/start.js
- /.scripts/version.js
- /.snapcraft/resources/initreplset.js
- /.travis/.*
- /client/.*
- /example-build-run.sh
- /install.sh
- /lib/.*
- /packages/autoupdate/.*
- /packages/meteor-accounts-saml/.*
- /packages/meteor-autocomplete/.*
- /packages/meteor-timesync/.*
- /packages/rocketchat-2fa/.*
- /packages/rocketchat-action-links/.*
- /packages/rocketchat-analytics/.*
- /packages/rocketchat-api/.*
- /packages/rocketchat-assets/.*
- /packages/rocketchat-authorization/.*
- /packages/rocketchat-autolinker/.*
- /packages/rocketchat-autotranslate/.*
- /packages/rocketchat-bot-helpers/.*
- /packages/rocketchat-cas/.*
- /packages/rocketchat-channel-settings-mail-messages/.*
- /packages/rocketchat-channel-settings/.*
- /packages/rocketchat-chatops/.*
- /packages/rocketchat-colors/.*
- /packages/rocketchat-cors/.*
- /packages/rocketchat-crowd/.*
- /packages/rocketchat-custom-oauth/.*
- /packages/rocketchat-custom-sounds/.*
- /packages/rocketchat-dolphin/.*
- /packages/rocketchat-drupal/.*
- /packages/rocketchat-emoji-custom/.*
- /packages/rocketchat-emoji-emojione/.*
- /packages/rocketchat-emoji/.*
- /packages/rocketchat-error-handler/.*
- /packages/rocketchat-favico/.*
- /packages/rocketchat-file-upload/.*
- /packages/rocketchat-file/.*
- /packages/rocketchat-github-enterprise/.*
- /packages/rocketchat-gitlab/.*
- /packages/rocketchat-google-natural-language/.*
- /packages/rocketchat-google-vision/.*
- /packages/rocketchat-highlight-words/.*
- /packages/rocketchat-i18n/package.js
- /packages/rocketchat-iframe-login/.*
- /packages/rocketchat-importer-csv/.*
- /packages/rocketchat-importer-hipchat-enterprise/.*
- /packages/rocketchat-importer-hipchat/.*
- /packages/rocketchat-importer-slack/.*
- /packages/rocketchat-importer/.*
- /packages/rocketchat-integrations/.*
- /packages/rocketchat-internal-hubot/.*
- /packages/rocketchat-irc/.*
- /packages/rocketchat-issuelinks/.*
- /packages/rocketchat-katex/.*
- /packages/rocketchat-ldap/.*
- /packages/rocketchat-lib/.*
- /packages/rocketchat-logger/.*
- /packages/rocketchat-mailer/.*
- /packages/rocketchat-mapview/.*
- /packages/rocketchat-markdown/.*
- /packages/rocketchat-mentions-flextab/.*
- /packages/rocketchat-mentions/.*
- /packages/rocketchat-message-attachments/.*
- /packages/rocketchat-message-mark-as-unread/.*
- /packages/rocketchat-message-pin/.*
- /packages/rocketchat-message-snippet/.*
- /packages/rocketchat-message-star/.*
- /packages/rocketchat-migrations/.*
- /packages/rocketchat-oauth2-server-config/.*
- /packages/rocketchat-oembed/.*
- /packages/rocketchat-otr/.*
- /packages/rocketchat-postcss/.*
- /packages/rocketchat-push-notifications/.*
- /packages/rocketchat-reactions/.*
- /packages/rocketchat-sandstorm/.*
- /packages/rocketchat-slackbridge/.*
- /packages/rocketchat-slashcommand-asciiarts/.*
- /packages/rocketchat-slashcommands-archiveroom/.*
- /packages/rocketchat-slashcommands-create/.*
- /packages/rocketchat-slashcommands-help/.*
- /packages/rocketchat-slashcommands-invite/.*
- /packages/rocketchat-slashcommands-inviteall/.*
- /packages/rocketchat-slashcommands-join/.*
- /packages/rocketchat-slashcommands-kick/.*
- /packages/rocketchat-slashcommands-leave/.*
- /packages/rocketchat-slashcommands-me/.*
- /packages/rocketchat-slashcommands-msg/.*
- /packages/rocketchat-slashcommands-mute/.*
- /packages/rocketchat-slashcommands-open/.*
- /packages/rocketchat-slashcommands-topic/.*
- /packages/rocketchat-slashcommands-unarchiveroom/.*
- /packages/rocketchat-slider/.*
- /packages/rocketchat-smarsh-connector/.*
- /packages/rocketchat-sms/.*
- /packages/rocketchat-spotify/.*
- /packages/rocketchat-statistics/.*
- /packages/rocketchat-theme/.*
- /packages/rocketchat-token-login/.*
- /packages/rocketchat-tooltip/.*
- /packages/rocketchat-tutum/.*
- /packages/rocketchat-ui-account/.*
- /packages/rocketchat-ui-admin/.*
- /packages/rocketchat-ui-flextab/.*
- /packages/rocketchat-ui-login/.*
- /packages/rocketchat-ui-master/.*
- /packages/rocketchat-ui-message/.*
- /packages/rocketchat-ui-sidenav/.*
- /packages/rocketchat-ui-vrecord/.*
- /packages/rocketchat-ui/.*
- /packages/rocketchat-version/.*
- /packages/rocketchat-videobridge/.*
- /packages/rocketchat-webrtc/.*
- /packages/rocketchat-wordpress/.*
- /private/.*
- /public/recorderWorker.js
- /publish_packages.sh
- /server/.*
- /tests/.*
component_depth: 1
languages:
- javascript
- ruby
- script
